# Generated by Django 4.1.2 on 2022-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='long_description',
            field=models.TextField(default='Here should be a short description'),
        ),
    ]
