# Generated by Django 4.1.2 on 2022-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_description_project_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
    ]
